#theme = 'ananke'
#baseURL = "https://truckee.xyz/"
#copyright = "truckee.xyz All Rights Reserved."

title = 'truckee.xyz'
baseURL = 'https://truckee.xyz/'
languageCode = "en-us"
theme = "ananke"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "truckee-xyz"
  favicon = "favicon.ico"
  site_logo = "truckee-xyz-background-dark-mode-3x-scale.png"
  description = "Useful information for Truckee, CA. Is your business or service missing? Want to see something else added? Do you want to provide feedback to make this site better? Please visit our Github page to let us know."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5

[[params.ananke_socials]]
name = "github"
url = "https://github.com/truckee-xyz"
