name: Deploy static content to staging.truckee.xyz
on:
  push:
    tags:
      - deploy-staging*
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truckee-xyz/truckee.xyz-hugo:latest
      options: --cpus 1
    steps:
      - name: Checkout repository truckee.xyz-hugo
        uses: actions/checkout@v4
        with:
          path: truckee.xyz-hugo
      - name: Checkout repository staging.truckee.xyz
        uses: actions/checkout@v4
        with:
          repository: truckee-xyz/staging.truckee.xyz
          path: staging.truckee.xyz
          token: ${{ secrets.STAGING_TRUCKEE_XYZ_GITHUB_PAT }}
      - name: run static site generator
        run: |
          cd truckee.xyz-hugo/truckee.xyz ; hugo;
      - name: commit static files to staging.truckee.xyz and trigger website update
        run: |
          cp -r truckee.xyz-hugo/truckee.xyz/public/* staging.truckee.xyz/docs/
          cd staging.truckee.xyz
          git config user.name github-actions-deploy-staging
          git config user.email github-actions-deploy-staging@truckee.xyz
          git add .
          git commit -m "github actions deploy staging"
          git push
