# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to staging.truckee.xyz
on:
  push:
    tags:
      - deploy-staging*
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truckee-xyz/truckee.xyz-hugo:latest
      options: --cpus 1
    steps:
#      - name: initialize static files
#        run: cd /app ; ls -a ; hugo
#      - name: Archive static files
#        uses: actions/upload-artifact@v4
#        with:
#          name: truckee-xyz-static-file
#          path: /app/public/
      - name: Checkout repository truckee.xyz-hugo
        uses: actions/checkout@v4
        with:
          path: truckee.xyz-hugo
      - name: Checkout repository staging.truckee.xyz
        uses: actions/checkout@v4
        with:
          repository: truckee-xyz/staging.truckee.xyz
          path: staging.truckee.xyz
      - name: initialize static files
        run: |
          cd truckee.xyz-hugo/truckee.xyz ; hugo ; pwd ; ls public/
#          cp public/* ../../staging/truckee.xyz/docs ;
#          cd ../.. ;
      - name: commit artifact to repo
        run: |
          pwd ;
          ls -a ;
#          which hugo ;
#          ls / ;
#          ls -a ../ ;
#          ls -a ../../ ;
#          git config user.name github-actions-deploy-staging
#          git config user.email github-actions-deploy-staging@truckee.xyz
#          git add .
#          git commit -m "github actions deploy staging"
#          git push

#  deploy-staging:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    steps:
#      - name: download-latest-static-files
#        uses: actions/download-artifact@v4
#        with:
#          name: truckee-xyz-static-file 
#      - name: Checkout repository staging.truckee.xyz
#        uses: actions/checkout@v4
#        with: 
#          repository: truckee-xyz/staging.truckee.xyz
#      - name: commit artifact to repo
#        run: 
#           ls -lash
#          git config user.name github-actions-deploy-staging
#          git config user.email github-actions-deploy-staging@truckee.xyz
#          git add .
#          git commit -m "github actions deploy staging"
#          git push
