#
name: Create and publish Hugo Docker images

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push dev container docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: dev-container
          push: true
          tags: ghcr.io/truckee-xyz/truckee.xyz-hugo:dev-container
      - name: Build and push debug container docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: ghcr.io/truckee-xyz/truckee.xyz-hugo:debug-container
          push: true
          tags: debug-container
      - name: Build and push hugo static build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: static-build
          push: true
          tags: ghcr.io/truckee-xyz/truckee.xyz-hugo:static-build
