name: Create and publish Hugo Docker images for local development purposes
on:
  push:
    tags:
      - build-site*
jobs:
  run-ssg:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truckee-xyz/truckee.xyz-hugo:ssg
      options: --cpus 1
    steps:
      - name: initiate container
        run: hugo
      - name: Archive static files
        uses: actions/upload-artifact@v4
        with:
          name: truckee-xyz-static-file
          path: /app/public
