name: Create and publish Hugo Docker images for local development purposes
on:
  push:
    tags:
      - build-site*
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truckee-xyz/truckee.xyz-hugo:base
      volumes:
        - /output:/app/public
      options: --cpus 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for dockerenv file
        run: echo
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: truckee-xyz-static-file
          path: output
