name: Create and publish Hugo Docker images for local development purposes
on:
  push:
    tags:
      - build-site*
jobs:
  run-ssg:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truckee-xyz/truckee.xyz-hugo:ssg
      volumes:
        - /output:/app/public
      options: --cpus 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: initiate container
        run: echo ""
      - name: Archive static files
        uses: actions/upload-artifact@v4
        with:
          name: truckee-xyz-static-file
          path: output
